project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Student Alcohol Consumption"
  author:
    - Jiaheng (Nielhs) Niu
  repo-url: https://github.com/NielsNiu/Project1
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - analysis.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


