# Introduction
Objectives:
Explore Alcohol Consumption Patterns
Relationship between student’s alcohol consumption (both weekday and weekend) and their academic performance (G1, G2, G3)
Examine Social and Family Factors
Investigate the influence of social behaviors (going out with friends, eca, romantic relationships…) and family-related variables (parental education, family size, cohabitation status, quality of parents) on alcohol consumption 
Assess Health and Study Impacts
How alcohol consumption correlates with age, health, absence…, focusing one student’s well-being and academic success

Research Questions:
Alcohol Consumption on Grades:
Does alcohol consumption during weekdays and weekends significantly affect students’ final grades? Regression line
Are the effects of alcohol consumption different when comparing weekday consumption vs weekend consumption? Two sample t-test
Correlation Between Social Factors and Alcohol Use
How does students’ tendency to go out with friends correlate with their weekday and weekend alcohol consumption? Compare correlation coefficients
Is being in a romantic relationship significant on alcohol consumption? p-value
Family Influence on Alcohol Consumption
Are there significant differences in alcohol consumption based on family relationship quality or family size? 组内对比
Predicting Grade
Can XXX predict students’ final grade?
